// ============================================================
//  build.js  —  Generates config.js from Vercel environment variables
//  Run automatically by Vercel before deployment.
//  Set AIRQO_TOKEN and OWM_TOKEN in your Vercel project settings.
// ============================================================

const fs   = require("fs");
const path = require("path");

const airqo = process.env.AIRQO_TOKEN || "";
const owm   = process.env.OWM_TOKEN   || "";

if (!airqo) console.warn("⚠  AIRQO_TOKEN is not set — AirQo features will be disabled.");
if (!owm)   console.warn("⚠  OWM_TOKEN is not set   — Weather features will be disabled.");

const content = `// Auto-generated by build.js — do not edit manually
const CONFIG = {
  AIRQO_TOKEN: "${airqo}",
  OWM_TOKEN:   "${owm}",
  COVERAGE_RADIUS_KM: 3,
  INTERP_GRID_SIZE:   40,
  REFRESH_INTERVAL_MS: 300000,
  CITIES: {
    Douala:  { lat: 4.0511, lng: 9.7085 },
    Yaoundé: { lat: 3.8667, lng: 11.5167 },
  },
  OWM_ONE_CALL: "https://api.openweathermap.org/data/3.0/onecall",
  OWM_AIR_BASE: "https://api.openweathermap.org/data/2.5/air_pollution",
  AIRQO_BASE:   "https://platform.airqo.net/api/v2",
};
CONFIG.USE_AIRQO = CONFIG.AIRQO_TOKEN !== "";
CONFIG.USE_OWM   = CONFIG.OWM_TOKEN   !== "";
`;

fs.writeFileSync(path.join(__dirname, "config.js"), content, "utf8");
console.log("✅  config.js generated from environment variables.");
